### ISSUE TITLE
Unexpected character in input:  '' (ASCII=2) 

### ISSUE THREAD

**Issue by cmodijk** [FriendsOfPHP/PHP-CS-Fixer#953]
When running the PHP-CS-Fixer from the phar version I get the following errors. I got some files with internal error's but how do I know what's wrong? 

```
PHP Warning:  Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
PHP Warning:  Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
PHP Warning:  Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
PHP Warning:  Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
```

```
./php-cs-fixer --version
PHP CS Fixer version 1.3 by Fabien Potencier (653cefb)
```

**Comment by ceeram** [comment]
Sounds like a bug in token_get_all(), what php version do you have, and what is the file contents causing this?

**Comment by ceeram** [comment]
Done some researching, most likely you have PHP 5.3 version and a file containing `__halt_compiler();` updating your php version would be the only solution here.
See https://bugs.php.net/bug.php?id=54089

**Comment by cmodijk** [comment]
No, I'm running PHP 5.5.20 and i'm not using `__halt_compiler();`

```
PHP 5.5.20 (cli) (built: Dec 21 2014 12:38:05) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by sstok** [comment]
ASCII=2 is a control character, is the file you're fixing corrupted or something?

**Comment by cmodijk** [comment]
After a little hunting I found that it's being caused by this file after stripping it down the error still occurs with this last piece of code. 

```
<?php

class NotificationCommand
{
    protected function composeEmail()
    {
        $emailSubject = $this->container->get("translator");

        return \Swift_Message::newInstance()
            ->setFrom(array("test@email.nl" => "test"))
            ->setBody($this->container->get("templating")->render(), "text/html");
    }
}
```

I have run it trough notepad++ with the `Show All Characters` setting on and this is the result

![schermafbeelding 2015-01-04 om 14 20 43](https://cloud.githubusercontent.com/assets/771041/5606089/25b7511c-941d-11e4-9f36-8b41c72e18b6.png)

**Comment by GrahamCampbell** [comment]
How is this file encoded? Try running our encoding fixer too.

**Comment by cmodijk** [comment]
My .php_cs

```
<?php

$config = Symfony\CS\Config\Config::create()
    ->fixers([
        "align_double_arrow",
        "align_equals",
        "concat_with_spaces",
    ]);

return $config;
```

**Comment by GrahamCampbell** [comment]
Enable the "encoding" fixer too please.

**Comment by cmodijk** [comment]
After enabling it it still exists

**Comment by GrahamCampbell** [comment]
Hmmm. Why have you enabled concat_with_spaces. You need to disable concat_without_spaces. It is enabled by default.

// cc @keradus this is exactly the sort of misunderstanding people have

**Comment by keradus** [comment]
offtop:
@GrahamCampbell and we already agreed to change it on 2.x line in the future, didn't we?
btw concat_with_spaces and concat_without_spaces works great together!

**Comment by keradus** [comment]
> Enable the "encoding" fixer too please.

`encoding` is enabled by default too

**Comment by keradus** [comment]
@cmodijk thanks for your bug report. We will work on it!

Test case extracted into PR: #954

**Comment by GrahamCampbell** [comment]
> encoding is enabled by default too

Yeh, I realised that and removed my comment earlier.

**Comment by cmodijk** [comment]
If I run with `align_double_arrow`, `align_equals`, `concat_with_spaces` and all the default ones I get this error. If I remove any one of them the problem does not happen.

**Comment by keradus** [comment]
It looks like a bug in `align_double_arrow` and I propose a solution this minute here: #954.

**Comment by cmodijk** [comment]
You are all amazing fast in responding to these things and the fixer tool itself is amazing. Great job to all of you!

**Comment by keradus** [comment]
Thanks, it is always nice to hear ;)
Remember that the solution is on PR state only, not merged yet. Need a review and regression. Then it will be released into 1.4-dev. Remember that dev aren't available via phar version. If you want it you will need to install it eg via composer. Or wait for 1.4 stable

**Comment by cmodijk** [comment]
That's not a problem for me for know I already did a checkout to debug some stuff myself. I edited the Fixer class to echo the file that is being use to find what file caused the problem because I was not sure it was the file in the error list. Offtopic is there a way to echo the filename being fixed for these kind purposes.

**Comment by keradus** [comment]
If you use verbose (`-v`) then it will be printed.
It is currently supported only for txt (so default) output. Not for json or xml.

**Comment by keradus** [comment]
Closing due to merge of #954
